services:

  db:
    image: postgres:12
#    command: postgres -c 'max_connections=${POSTGRES_MAX_CONNECTIONS}'
#    shm_size: '2g'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - '5432:5432'

  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  web:
    build: ./Web   # фронт находится в папке webka
    ports:
      - '3000:3000'
    volumes:
      - ./Web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    restart: always

volumes:
  postgres_data: